### ISSUE TITLE
Hide cheated games

### ISSUE THREAD

**Issue by niklasf** [niklasf/lila-openingexplorer#110]
Ideas:

* Mitigate by excluding provisional ratings from top games
* Blacklist of users on display (ornicar/lila#8378)

**Comment by Cubox** [comment]
Unsure which would be easier to implement, but you could also calculate which ratings were the highest ever obtained by legitimate players. Then block all games with ratings above that to be displayed. You could also give a pass for titled players from that.

This would remove the insanely high ratings games from top games. Top games for a board without any moves would be from leaders in the TC in question.

**Comment by jxu** [comment]
Yeah I knew something was up when they were showing "3500 rated" players

**Comment by niklasf** [comment]
In the [recently deployed version](https://lichess.org/forum/lichess-feedback/opening-explorer-tweaks), "top games" are no longer the absolutely highest rated games. Instead, they are recent games from the highest rating bracket. So insanely high ratings reached by manipulation will no longer stick to the top indefinitely. I am tempted to say this is good enough.
