### ISSUE TITLE
Downloading the databases

### ISSUE THREAD

**Issue by YodaEmbedding** [niklasf/lila-openingexplorer#115]
Where can I download a precomputed openings database? With the [1600/1800/2000/2200/2500+] and [Bullet/Blitz/Rapid/Classical] and [Lichess/Masters] and [W/D/L] breakdown.

I was hoping to do some data analysis (or rather, develop an opening repertoire generating tool).

I checked https://database.lichess.org/, but the opening explorer database doesn't seem to be there. It would also be nice to have variants (especially Crazyhouse), if available.

**Comment by niklasf** [comment]
The opening explorer database is not available for download. Its in a custom format that would require running the lila-openingexplorer server anyway (or reimplementing parts of it). At that point you might as well also reindex the database from the PGNs published on https://database.lichess.org/.
