### ISSUE TITLE
select multiple speeds (like blitz+classical)

### ISSUE THREAD

**Issue by ornicar** [niklasf/lila-openingexplorer#13]
I'm building the explorer config UI

![](https://i.imgur.com/iS4eNsh.png)

And I think it would make sense to select multiple speeds, notably blitz+classical, since the opening stage should not be too different and it would give more result to select both.

Feasible?

**Comment by niklasf** [comment]
Yep. We have the numbers and can simply sum them up. Looking good, btw!

**Comment by niklasf** [comment]
all done
