### ISSUE TITLE
ui

### ISSUE THREAD

**Issue by niklasf** [niklasf/lila-openingexplorer#19]
* [x] allow variant selection in /analysis

---

* [x] hangs when clicking on drops, in crazyhouse
* [x] inconsistency: `P@c3` from the api, `@c3` in move list

---

* [x] show recent/top games

---

* [x] do not (try to) display number if bar is too thin
* [x] master games unavailable for variants, do not show the option
* [x] opening book available during correspondence games?
* [x] if no games are found, remind the user of the filter settings

---

* [x] consider highlighting squares as moves are hovered
* [x] consider showing average rating as tooltip
* [x] right align numbers
* [x] thousands spacing
* [x] master games imported by: the user that first clicked them
* [x] consider cutting off the percent sign if bar is thinner than ~ 20%
* [x] color choice: i like high contrast color for the headers. it's much better than the old version. the buttons in the settings are green. buttons in the existing user preferences are orange. maybe reuse that?

**Comment by ornicar** [comment]
> inconsistency: P@c3 from the api, @c3 in move list

That's because the move list uses a chess font that doesn't have a char for pawns.

**Comment by niklasf** [comment]
tooltips also done. nice

**Comment by niklasf** [comment]
* [ ] consider cutting off the percent sign if bar is thinner than ~ 20%

**Comment by Unihedro** [comment]
re cutting off the percent sign: will elevating the z-index and giving it a unique presentation (strong text shadow?) work?

**Comment by niklasf** [comment]
it might. for reference, here's the situation:
![image](https://cloud.githubusercontent.com/assets/402777/13008482/d8c11862-d196-11e5-968f-b9964c8a320a.png)

**Comment by Unihedro** [comment]
for the record, I tried this tweak, not sure if it's helpful:

![](https://files.slack.com/files-pri/T0HL8V171-F0M452SH0/pasted_image_at_2016_02_12_10_07_pm.png?pub_secret=9a4fa47889)

```css
`element.style` {
    margin-left: -2.8%; /* inline? */
}
.explorer_box .bar span span.overflow {
    z-index: 3;
    position: absolute;
    display: block;
    border: none;
    text-shadow: 0 0 5px black;
}
```
I wrapped the text in an additional span such that the outer span takes up space while the inner span positions the text..
