### ISSUE TITLE
game links

### ISSUE THREAD

**Issue by ornicar** [niklasf/lila-openingexplorer#26]
I need to know the players names and the year to display them.

master games: store in kyoto? separate DB maybe? or use the existing PGN DB and read the game tags?

lichess games: data can be retrieved from lichess DB on demand. But I see the initial position has 31 recent games plus 31 top games. Do we really need all that? How about 4 each?

**Comment by niklasf** [comment]
About the master database: If tag parsing works reasonably well performance wise, let's do that.

Lichess games: These numbers are actually an artifact of the packing scheme. Not all of them are valid recent/top games. I'll fix that and make the numbers configurable.

**Comment by ornicar** [comment]
lichess PGN tag parsing is slow because it aims at being tolerant and support the widest range of user-posted PGN files. A performant parser should be written for the explorer, since the tags are guaranteed to be normalized.

lichess games: lichess could wrap the request to the explorer, and use its DB to enrich the games with player names and date.
