### ISSUE TITLE
ply in links to game might be off due to transpositions

### ISSUE THREAD

**Issue by niklasf** [niklasf/lila-openingexplorer#34]
not sure if we care enough to fix this: if by transposition the same position is reached with different numbers of moves, the specific ply we link to might be off

**Comment by ornicar** [comment]
I don't see how to fix that.

**Comment by Vinvin20** [comment]
Position search in the game but that's a quite lot of work. 
May be later ?...

**Comment by Vinvin20** [comment]
But, please, give the approximate position to start.

**Comment by niklasf** [comment]
done via https://github.com/ornicar/scalachess/blob/18edd6eb2de3b408506ff7df194d73fcb8fce3a7/src/main/scala/Replay.scala#L101
