### ISSUE TITLE
top games not filtered by time control

### ISSUE THREAD

**Issue by niklasf** [niklasf/lila-openingexplorer#38]
@ornicar: bummer ... i just noticed top games are not filtered by time control. good time to realize this, with indexing almost complete?

i'll figure out the best we can do without complete reindexing. then let's talk about the options.

**Comment by niklasf** [comment]
i found another issue: https://github.com/ornicar/lila/commit/9ff9296b27231f313d8554e477ebc2b4b8afb7e0#commitcomment-16216028

we won't get around reindexing

**Comment by ornicar** [comment]
okay then.

I did https://github.com/ornicar/lila/commit/6cf03d25feebe01614166ca61589f6b039e21ebc

Let me know when the indexer is ready to go.

**Comment by niklasf** [comment]
fixed
