### ISSUE TITLE
encoding issue

### ISSUE THREAD

**Issue by ornicar** [niklasf/lila-openingexplorer#39]
![](http://rincevent.net/~lucas/utfail.png)

Reproduce: 

- go to http://lichess.org/XlcAUtSa#3
- select master games
- see top games

imported game: http://lichess.org/b9GHOXu0

**Comment by niklasf** [comment]
this is latin-1 sent as utf-8

**Comment by Vinvin20** [comment]
His real first name is "Jörg Kracht".
https://de.wikipedia.org/wiki/J%C3%B6rg_Kracht

**Comment by niklasf** [comment]
production database is finally fixed. only thing left to do is getting rid of already imported games (or gradually upgrading them, as planned)

**Comment by niklasf** [comment]
see ornicar/lila#1696
