### ISSUE TITLE
a look at the competition

### ISSUE THREAD

**Issue by ornicar** [niklasf/lila-openingexplorer#4]
[ChessTempo](http://chesstempo.com/game-database.html)
![](https://i.imgur.com/BLcmIB6.png)

---

[chess24](https://chess24.com/en/analysis)
![](https://i.imgur.com/yIJaM2Y.png)

**Comment by ornicar** [comment]
I like the average rating of a move they both have. Is that thing our backend can reasonably provide?

**Comment by niklasf** [comment]
If we do the rating groups by average (instead of minimum) we get it almost entirely for free. If not, it still might not be too expensive.

**Comment by niklasf** [comment]
![image](https://cloud.githubusercontent.com/assets/402777/12867453/89ca2a7a-ccee-11e5-99f2-c1c60401501e.png)
http://www.shredderchess.com/online-chess/online-databases/opening-database.html

**Comment by niklasf** [comment]
![image](https://cloud.githubusercontent.com/assets/402777/12867460/cef94fe0-ccee-11e5-8cd8-a85791231490.png)
http://www.chessgames.com/perl/explorer?node=77705&move=2&moves=Nf3.d5&nodes=74.77705

**Comment by niklasf** [comment]
![image](https://cloud.githubusercontent.com/assets/402777/12867475/269891ac-ccef-11e5-8cae-f0181a3f3c2c.png)
https://www.chess.com/explorer/

**Comment by niklasf** [comment]
http://www.365chess.com/opening.php?m=4&n=195&ms=e4.c5.Bc4&ns=3.3.195

* Recent games
* Played frequently by ...

**Comment by ornicar** [comment]
[chess.com v3](https://www.chess.com/explorer)

![](https://i.imgur.com/1HMEVbZ.jpg)

**Comment by ornicar** [comment]
Closing since we outrun them all.
