### ISSUE TITLE
no positions found when king is captured in antichess

### ISSUE THREAD

**Issue by niklasf** [niklasf/lila-openingexplorer#40]

**Comment by niklasf** [comment]
moves arrive at explorer.

strongly suspect an issue with castling rights. moved kings can be captured, no problem.

**Comment by niklasf** [comment]
ornicar/scalachess#66

**Comment by niklasf** [comment]
keeping this open, as a reminder that some things have to be reindexed

**Comment by ornicar** [comment]
Changes are deployed.

**Comment by niklasf** [comment]
also fixed with reimport on homer
