### ISSUE TITLE
Wrong move notation

### ISSUE THREAD

**Issue by mgrabovsky** [niklasf/lila-openingexplorer#47]
The opening explorer shows an invalid move in the Latvian Gambit after 1.e4 e5 2.Nf3 f5 3.Nxe5. It shows Qxe7 as a possible continuation, and although Qe7 is a valid move, it's not a capture.

![ss 2016-07-31 at 05 17 16](https://cloud.githubusercontent.com/assets/134321/17277430/ca92178c-5742-11e6-8abd-b1cb4d2b1f95.png)

I'm not sure if this is an issue of this component specifically or whether I should file it under lila, but here we go.

**Comment by niklasf** [comment]
Thanks, fixed. I am experimenting with a new encoding format to improve handling of transpositions. This slipped through. Let me know if you find anything else :)
