### ISSUE TITLE
Weird move listed

### ISSUE THREAD

**Issue by mgrabovsky** [niklasf/lila-openingexplorer#48]
The opening explorer suggests a very strange move in the Sicilian Najdorf after 1.e4 c5 2.Nf3 d6 3.d4 cxd4 4.Nxd4 Nf6 5.Nc3 a6 6.Be3 Ng4, the move Qxg4 is listed is having been played in one game in the masters database. However, upon playing that move, no game is shown.

![screenshot from 2016-08-12 13-54-44](https://cloud.githubusercontent.com/assets/134321/17621617/c48771f6-6094-11e6-9ac9-1b52a7736e73.png)

**Comment by niklasf** [comment]
This is the game: https://de.lichess.org/RxmL6u2H#25

It ends right there with a draw, so no more moves are shown.Very strange, but apparently not an opening-explorer bug.

(Btw. thanks for keeping an eye on the explorer and reporting these issues! Much appreciated)

**Comment by mgrabovsky** [comment]
Ah, thanks. Very strange, indeed.
