### ISSUE TITLE
Include very short games

### ISSUE THREAD

**Issue by niklasf** [niklasf/lila-openingexplorer#59]

**Comment by gcp** [comment]
Right now there's an effect that if multiple games reach the same terminal position, they seem to only be counted once. This could skew the statistics a bit for opening traps. (Obvious example: scholars' mate).

Not sure if it's related to this or not.

**Comment by niklasf** [comment]
Fixed with v3 and live.

@gcp: Can you please check if the issue you were seeing is still happening?

Btw. the masters database is deduplicated by terminal position, to avoid having to deduplicate by names and dates, which vary in precision and spelling in various sources. The Lichess database is not deduplicated like that.
