### ISSUE TITLE
Nimzo-Indian Defense E20 Premature Naming

### ISSUE THREAD

**Issue by landry314** [niklasf/lila-openingexplorer#61]
The Nimzo-Indian Defense E20 is described as:

1. d4 Nf6 2. c4 e6 3. Nc3 Bb4

but if you make the moves

1. d4 Nf6 2. c4 e6 3. Nc3

it is already prematurely calling this the Nimzo-Indian Defense.

If black does not make the move Bb4 and makes any other move the game will be described as a Nimzo-Indian Defense game which it is not.

Proof of the official E20 game moves:

https://www.365chess.com/eco/E20
http://www.chessgames.com/chessecohelp.html
https://en.m.wikipedia.org/wiki/Nimzo-Indian_Defence

The Bb4 move is an essential part of this opening...

**Comment by landry314** [comment]
Is this the right place to report this?

**Comment by niklasf** [comment]
Thanks @landry314, will fix. The right repository for similar issues would probably be https://github.com/ornicar/scalachess.

**Comment by niklasf** [comment]
Done. It can take a while before this lands in production.
