### ISSUE TITLE
Cheated games

### ISSUE THREAD

**Issue by Nicals** [niklasf/lila-openingexplorer#66]
I analyzed a line in the Lichess opening explorer, and one of the Top game listed was a game that ended with cheat detection.
I'm not sure engine games should be indexed by the opening explorer and displayed as examples.

The game in question: https://lichess.org/izhNCrJG
The line analyzed was: 

 ```
r2qk2r/pp1nbpp1/2p1pn1p/7P/3P4/3Q1NN1/PPPB1PP1/2KR3R w kq - 4 13
```

The game in question appeared with the explorer settings at Lichess Database, all level, Rapid and Classical time control.

Not sure if this the good repository for this issue, sorry if not the case.

**Comment by niklasf** [comment]
Yes, this is the right place to discuss this issue.

I am tempted not to do anything about this. When closing an account for cheating, they might have played thousands of games, making for large database updates. And openings of cheated games are not necessarily bad data ...
